project:
  name: quickstart-boomi-molecule
  owner: quickstart@amazon.com
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
tests:
  quickstart-boomi-molecule-password:
    regions:
      - us-east-2
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      BoomiAccountID: override
      BoomiUsername: override
      HostedZoneID: override
      KeyPairName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RemoteAccessCIDR: 127.0.0.1/32
      MoleculeFQDN: override
    template: templates/boomi-molecule-master.template.yaml
  quickstart-boomi-molecule-password-private-alb:
    regions:
      - us-east-2
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      BoomiAccountID: override
      BoomiUsername: override
      HostedZoneID: override
      KeyPairName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RemoteAccessCIDR: 127.0.0.1/32
      MoleculeFQDN: override
      PrivateALB: 'true'
    template: templates/boomi-molecule-master.template.yaml
  quickstart-boomi-molecule-password-no-alb:
    regions:
      - us-east-2
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      BoomiAccountID: override
      BoomiUsername: override
      HostedZoneID: override
      KeyPairName: override
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RemoteAccessCIDR: 127.0.0.1/32
      MoleculeFQDN: override
      DeployALB: 'false'
    template: templates/boomi-molecule-master.template.yaml
  # quickstart-boomi-molecule-install-token:
  #   regions:
  #     - us-east-2
  #   parameters:
  #     AvailabilityZones: $[taskcat_genaz_2]
  #     BoomiAccountID: override
  #     BoomiUsername: override
  #     BoomiInstallToken: override
  #     HostedZoneID: override
  #     KeyPairName: override
  #     QSS3BucketName: $[taskcat_autobucket]
  #     QSS3BucketRegion: $[taskcat_current_region]
  #     RemoteAccessCIDR: 127.0.0.1/32
  #     MoleculeFQDN: override
  #     PrivateALB: 'true'
  #   template: templates/boomi-molecule-master.template.yaml
