// There are generally two deployment options. If additional are required, add them here

This Quick Start provides two deployment options:

* *Deploy {partner-product-name} into a new VPC (end-to-end deployment)*. This option builds a new AWS environment consisting of the VPC, subnets, NAT gateways, security groups, bastion hosts, and other infrastructure components. It then deploys {partner-product-name} into this new VPC.
* *Deploy {partner-product-name} into an existing VPC*. This option provisions {partner-product-name} in your existing AWS infrastructure.

The Quick Start provides separate templates for these options. It also lets you configure Classless Inter-Domain Routing (CIDR) blocks, instance types, and {partner-product-name} settings, as discussed later in this guide.

=== Authentication

In addition to the two deployment options, there are two authentication options for deployment.

** Deploy with Account ID, Username, API Key, and Installation Token

** Deploy with authorized Account ID, Username, and Password (Not MFA compatible)

You will need to choose one method or the other. If you are unsure of how to create an Installation Token or API Token/Key, see link:#_creating_an_installation_token[Creating an Installation Token] in this guide for steps or contact your administrator.